version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  job-scraper:
    build:
      context: .
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./app:/app/app  # ✅ mount your code into the container
    depends_on:
      - redis
volumes:
  pgdata: